# print("welcome to SBI")
# print("swipe your card")
# pin=input("enter the pin")
# amount=50000
# if pin:
#     transaction="balance enquiry","withdraw money","deposit"
#     print("choose your transacation")
#     print("1 balance enquiry")
#     print("2 withdraw money")
#     print("3 deposit")
#     print("4 transfer money")
#     print("5 quit")
#     trans=input("transacation")
#     if trans=="balance enquiry":
#         balance=input("enter the current or saving")
#         if balance=="saving":
#             print("your account balance is,ammount")
#     else:
#         print("zero balance")
#     if trans=="withdraw money":
#         amount=int(input("enter your money to proceed"))
#         if amount<=50000:
#             print("collect your cash now your money amount,amount is left")
#             print("thanks for visiting sbi")
#     if trans=="change your pin":
#         change=input("enter new pin")
#         if change=="change pin":
#             print("your pin has been successfully")
#         else:
#             print("enter a valid pin")
#     if trans=="transfer money":
#         transfer=int(input("enter the amount"))
#         if transfer<=20000:
#             print("your transaction is successfully")
#             amount-transfer,"is left in your account"
#         else:
#             print("enter valid amount for transcation")
#     if trans=="quiet":
#         quiet=input("press yes to quiet ")
#         if quiet==("yes"):
#             print("quiet")
#         else:
#             print("choose any transcation please")
# else:
#     print("wrong password")



print("welcome to commonbank")
print("please enter your card")
print("please select your language")
language=input("enter the language")
if language==("enter the pin number"):
    pin=input("enter the pin number")
    if pin==1729:
        print("transcations: 1)withdraws 2)blank query 3)pin generate 4)cliposite 5)exit:")
    transcation=int(input("choose your transacation")) 
    amount=2000
    if transcation==1:
        withdraw=int(input("enter withdraw"))
        if withdraw<=amount:
            print("collect your cash, withdraw") 
            print("remaining Balance is, amount withdraw")
        else:
            print("not withdraw")
    elif transcation==2:
        print("your available balance is,amount")
    else:
        print("thank you for visiting")
        print("thank you for visiting")
    elif transcation==3:
    pin generate=(int(input("enter the new pin")))
    if pin generate==1729:
        print("new pin generate is successfully")
    else:
        print("once again thanks for visiting")
        elif transacation==4:
            deposite=int(input("enter the deposit amount"))
            if deposit amount>=amount>=1000:
                print("your deposit is complete,"a+d)
                else:
                    print("not deposit")
                    elif transation==5:
                        print("exit on thank you")
                        else:
                            ("exit or thank you")
else:
    print("invalid data")
        
        